[package]
name = "physarum"
version = "0.1.0"
authors = ["mindv0rtex <mindv0rtex@users.noreply.github.com>"]
edition = "2018"

[dependencies]
image = "*"
itertools = "*"
rand = "*"
rayon = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "trig"
harness = false